### ISSUE TITLE
the keys: impossible d'ajouter une intégration dans home assistant

### ISSUE THREAD

**Issue by slevignac** [KevinBonnoron/the_keys#33]
Bonjour
j'ai un problème pour ajouter l'intégration à home assistant.
La première fois que j'ai tenté, cela me remontait que l'état de la batterie de ma serrure (et à -344%), j'ai donc supprimer l'appareil de home assistant, et depuis le terminal, supprimer tout les répertoires faisant référence à the_keys.
Maintenant, je re-essaie, mais cela ne me propose plus l'intégration the keys.
En terminal, depuis `/root/config` ou depuis `/root/config/custom_components`, je fais `git clone https://github.com/KevinBonnoron/the_keys`, mais après reboot de mon home-assistant(depuis outil de développement, et même en essayant de reboot la vm), aucune intégration n'est proposée...
Est-ce que j'oublie de faire quelque chose?
J'ai même essayé de faire un cp -R /root/config/the_keys/custom_components /root/config/custom_components/the_keys, mais cela ne change rien.
J'utilise HAOS sur une VM (  OS Version:               Home Assistant OS 15.1 ,   Home Assistant Core:      2025.3.4)
J'ai également essayé de faire un `grep "keys" *log*` pour voir si il y aurait une trace dans les  logs, mais cela ne remonte rien.
j'ai modifié mon configuration.yaml pour mettre :
```
logger:
  default: debug
  logs:
    homeassistant.components.webhook: debug
    homeassistant.components: debug
    custom_components.the_keys: debug
```
Mais je n'ai toujours aucune trace de log en cherchant the_keys ...
Merci pour votre future aide.
Bonne journée.
